### ISSUE TITLE
Settle on naming?

### ISSUE THREAD

**Issue by benlindsay** [apiad/streamlit-pydantic#1]
Should we leave it streamlit_pydantic or change to streamlit-pydantic?

My impression is the most common naming convention, for better or worse, is "-" in the package name, even though we obviously need a "_" in the source directory. The consistency is nice when the package name and source directory are the same though, so I don't feel super strongly about it...I just typically try to follow common naming conventions.

Thoughts?

**Comment by apiad** [comment]
Agree! I think the package can be named `streamlit-pydantic` in pypi (`pip install streamlit-pydantic`) and imported as `from streamlit_pydantic import ...`.

If you feel like, go ahead a grab the name on Pypi.

**Comment by apiad** [comment]
We can change the name of the repository as well to `streamlit-pydantic`, it will break the remotes but for now it's just and me :)

**Comment by leynier** [comment]
Then I'll wait for the name change to make my fork 😅

**Comment by leynier** [comment]
@apiad @benlindsay guys, a package with the name `streamlit-pydantic` already exists in PyPi.

https://github.com/lukasmasuch/streamlit-pydantic
https://pypi.org/project/streamlit-pydantic

**Comment by benlindsay** [comment]
Yeah, looks like he created that very recently and made it do almost exactly what we're looking to do. @apiad I know you were excited to build this, and I was too, but I think it probably makes sense to go join forces with Lukas on this instead of work on this in parallel

**Comment by leynier** [comment]
Wow, the other repository was created today. Was the idea mentioned by any social network?

**Comment by benlindsay** [comment]
Yeah, this started from a twitter thread: https://twitter.com/ben_j_lindsay/status/1413233908217430017?s=20

Lukas had built opyrator, which includes this functionality inside it, but @apiad and I wanted this functionality as a standalone package, then Lukas built it really quick by extracting his own code into a separate package, so that made this all a lot faster 😁

**Comment by leynier** [comment]
Yeah, that was 😅

**Comment by apiad** [comment]
> Yeah, looks like he created that very recently and made it do almost exactly what we're looking to do. @apiad I know you were excited to build this, and I was too, but I think it probably makes sense to go join forces with Lukas on this instead of work on this in parallel

Absolutely! He seems to be far more advanced than we. If it fits our use case (on a superficial look it seems so) I'm perfectly fine with using it and contributing there. That's the open-source spirit!

**Comment by apiad** [comment]
One thing I'd like to have is an easy way to do:

```python
obj = st.pydantic_input(Model, ...)
```

To get the instance directly, especially if all attributes have default values and everything is nice and simple. This would be my first suggestion to Lukas's implementation. Other than that it seems very very cool.

**Comment by benlindsay** [comment]
Exactly my thought as well. I'm hoping Lukas is amenable to that API change

**Comment by apiad** [comment]
Yeah we can always fork and do it ;) But I think it's a sensible thing to have...

**Comment by benlindsay** [comment]
Yeah, maybe he has good reason to store the intermediate values in session_state, but i don't see any reason not to return the pydantic object too

**Comment by apiad** [comment]
I think the reason will be to partially construct the object since you have to render a bunch of widgets. And it sounds like a reasonable way of doing it.  That's why he has a `parse_obj` or something like that, to explicitly build the instance. Maybe adding something like `return_obj=True` to the `pydantic_input` would work and not introduce any breaking changes to the API...
